openapi: 3.1.0
info:
  version: 1.0.0
  title: <SportPoint App>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <Service for working with backend documentation. >
  contact:
    email: oksana.tanashuk@gmail.com
tags:
  - name: Auth
    description: Auth operations.
  - name: UserProfile
    description: Operations about users profiles.
  - name: SearchUserProfile
    description: Search operations
servers:
  - url: https://sportpoint-backend.onrender.com
  - url: http://localhost:3000
paths:
  /auth/signup:
    post:
      $ref: '../swagger/paths/signup/post.yaml'
  /auth/signin:
    post:
      $ref: '../swagger/paths/signin/post.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/logout/post.yaml'
  /auth/refresh/current:
    get:
      $ref: '../swagger/paths/refreshCurrent/get.yaml'
  /auth/verify/:verificationToken:
    get:
      $ref: '../swagger/paths/verify/{id}/get.yaml'
  /auth/verify:
    post:
      $ref: '../swagger/paths/verify/post.yaml'
  /auth/send/verify:
    post:
      $ref: '../swagger/paths/send/verify/post.yaml'
  /auth/delete/account:
    delete:
      $ref: '../swagger/paths/deleteAccount/delete.yaml'
  # /auth/change/password:
  #     $ref: '../swagger/paths/updatePassword/update.yaml' 
  /profile:
    get:
      $ref: '../swagger/paths/userProfile/get.yaml'
    delete:
      $ref: '../swagger/paths/userProfile/delete.yaml'
    patch:
      $ref: '../swagger/paths/userProfile/patch.yaml'
    post:
      $ref: '../swagger/paths/userProfile/post.yaml'
  /search/by-name:
    get:
      $ref: '../swagger/paths/search/get.yaml'
  /card/club:
    get:
      $ref: '../swagger/paths/cards/club/get.yaml'
  /cards/coach:
    get:
      $ref: '../swagger/paths/cards/coach/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
